version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_CONNECTION: mysql
      DB_HOST: sql12.freemysqlhosting.net
      DB_PORT: 3306
      DB_DATABASE: sql12750390
      DB_USERNAME: sql12750390
      DB_PASSWORD: uruP7GX1YI
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/public
    ports:
      - 8080:8080
