version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_CONNECTION: mysql
      DB_HOST: sql12.freemysqlhosting.net
      DB_PORT: 3306
      DB_DATABASE: sql12750390
      DB_USERNAME: sql12750390
      DB_PASSWORD: uruP7GX1YI
    depends_on:
      - php
      - mysql

  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - .:/var/www
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/public
    ports:
      - 8080:8080
    depends_on:
      - php
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sql12750390
      MYSQL_USER: sql12750390
      MYSQL_PASSWORD: uruP7GX1YI
    ports:
      - 3306:3306

networks:
  app_network:
    driver: bridge
